package com.clps.demo.domain;
// Generated 2018-1-12 10:20:57 by Hibernate Tools 5.2.6.Final

import java.util.Date;

/**
 * Orderstatus generated by hbm2java
 */
public class Orderstatus implements java.io.Serializable {

	private OrderstatusId id;
	private Date timestamp;
	private String status;

	public Orderstatus() {
	}

	public Orderstatus(OrderstatusId id, String status) {
		this.id = id;
		this.status = status;
	}

	public OrderstatusId getId() {
		return this.id;
	}

	public void setId(OrderstatusId id) {
		this.id = id;
	}

	public Date getTimestamp() {
		return this.timestamp;
	}

	public void setTimestamp(Date timestamp) {
		this.timestamp = timestamp;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
